spring.main.sources: com.schlaepfer.health.systemone.SystemOneSpringBootRouter
shell.auth.simple.user.password: password
shell.ssh.port: 9001
server.port: 9000

netty.port: 8887
netty.hostname: localhost

springws:
  url.mapping: /systemone-api/*
  servlet.name: spring-ws

---
spring:
  profiles: test

  
