spring.main.sources: com.schlaepfer.health.sap.SapSpringBootRouter
shell.auth.simple.user.password: password
shell.ssh.port: 9051
server.port: 9050

activemq:
  brokerurl: tcp://localhost:61616
  maxConnections: 6

---
spring:
  profiles: test

connection:
  address: chrzmdb1017.eu.hcnet.biz
  port: 7019
  
